const addons = [
  {
    serial: "A1",
    name: "Extra Remove Floor Tile",
    image: "../photos/addon040406/a1.jpg",
    detail: "Remove Floor Tile in Foyer and Hallway Area",
    price: "380",
    isChecked: false,
  },
  {
    serial: "A2",
    name: "Demolish Kitchen Wall",
    image: "../photos/addon040406/a2.jpg",
    detail: "Remove Kitchen wall to Open Concept with 4 inch potligh x 6",
    price: "5380",
    isChecked: false,
  },
  {
    serial: "A3",
    name: "Ventilation for Hood Fan",
    image: "../photos/addon040406/a3.jpg",
    detail: "Modify and Connect Ventilation for Hood Fan",
    price: "1260",
    isChecked: false,
  },
  {
    serial: "A4",
    name: "Exhaust Pipe for Dryer",
    image: "../photos/addon040406/a4.jpg",
    detail: "Open and Finish Bulkhead and Add Exhaust for Dryer",
    price: "2510",
    isChecked: false,
  },
  {
    serial: "A5",
    name: "Laundry Door ",
    image: "../photos/addon040406/a5.jpg",
    detail: "Remove Existing Laundry Door and Frame and Supply and Install new Double Door in 60 inch x 80 inch",
    price: "3920",
    isChecked: false,
  },
  {
    serial: "A6",
    name: "Kitchen Paint Match Similar with Living Room",
    image: "../photos/addon040406/a6.jpg",
    detail: "Bemjamin Moore OC-122 Cotton Balls",
    price: "0",
    isChecked: false,
  },
  {
    serial: "A7",
    name: "Add Island in Kitchen",
    image: "../photos/addon040406/a7.jpg",
    detail: "With 3 Cabinets(Two Double Door and One Drawer",
    price: "2440",
    isChecked: false,
  },
]
